// Code generated by Slice Machine. DO NOT EDIT.

import GridImages from './GridImages';
import Hero from './Hero';

export {
	GridImages,
	Hero,
};

export const components = {
	grid_images: GridImages,
	hero: Hero,
};
