// Code generated by Slice Machine. DO NOT EDIT.

import BackgroundedTitle from './BackgroundedTitle';
import GridImages from './GridImages';
import Hero from './Hero';

export {
	BackgroundedTitle,
	GridImages,
	Hero,
};

export const components = {
	backgrounded_title: BackgroundedTitle,
	grid_images: GridImages,
	hero: Hero,
};
